### ISSUE TITLE
Criteria not being rendered when _search facet 

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/pawtucket2#105]
I have narrowed down an issue where the criteria listing is showing blank if the criteria is of type `_search`

In this commit https://github.com/collectiveaccess/pawtucket2/commit/c9cd425d6be017ca11f798d4547bde9ccc6013aa on line 415 of app/controllers/SearchController.php

If I comment this block out, then it works as I am expecting.  

It detects the criteria as existing, but `$criterion['value']` is empty.

Best way to reproduce this is to do a search on the `_fulltext` field of the advanced search, or via the 'search within results' of the browse.

**Comment by collectiveaccess** [comment]
That commit doesn't include SearchController. Can you post the id for the commit where you found the problem?

**Comment by Monica-Wood** [comment]
Apologies, I was off by one. Its part of the merge, bb6acbc02fe4d29594023618ece0601ea804852f

**Comment by Monica-Wood** [comment]
Within that merge it was this commit 380eda94fbb450293492c60b8f09b485281b9e75

**Comment by Monica-Wood** [comment]
Tested and working
