### ISSUE TITLE
Get related objects has started failing in detail view

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/pawtucket2#106]
Using this snippet:

```
{{{<ifcount code="ca_objects" min="2">
		<div class="container">
			<h2>Items in Collection</h2>
			<div class="row">
				<div id="browseResultsContainer">
					<?php print caBusyIndicatorIcon($this->request).' '.addslashes(_t('Loading...')); ?>
				</div><!-- end browseResultsContainer -->
			</div><!-- end row -->
		</div>
			<script type="text/javascript">
				jQuery(document).ready(function() {
					jQuery("#browseResultsContainer").load("<?php print caNavUrl($this->request, '', 'Search', 'objects', array('search' => 'collection_id:^ca_collections.collection_id'), array('dontURLEncodeParameters' => true)); ?>", function() {
						jQuery('#browseResultsContainer').jscroll({
							autoTrigger: true,
							loadingHtml: '<?php print caBusyIndicatorIcon($this->request).' '.addslashes(_t('Loading...')); ?>',
							padding: 20,
							nextSelector: 'a.jscroll-next'
						});
					});
					
					
				});
			</script>
		</ifcount>}}}
```

Which was working the last time I looked (couple of weeks ago?). Has started to produce this

![Screenshot 2024-05-16 at 4 49 58 PM](https://github.com/collectiveaccess/pawtucket2/assets/25235893/d2d9137d-3b93-4d8b-a3a6-61c33933d410)

Happens in the collections detail as above and entities detail views when trying to get a search result of related objects (the entity view has related objects and collections done the same way and only objects throws the error)

**Comment by collectiveaccess** [comment]
What do the logs say?

**Comment by Monica-Wood** [comment]
The logs have nothing to say for themselves.  Nginx, PHP and App logs ... zilch.

**Comment by Monica-Wood** [comment]
I checked with default theme and doing it there. so not my theme settings.

**Comment by Monica-Wood** [comment]
So just ignore me. I changed the Browse view to be 'items' instead of 'objects'. Still curious why it didn't work on the default one though, some sort of cache seeping through maybe.
