### ISSUE TITLE
external_applications.conf to be brought inline with providence?

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/pawtucket2#108]
I was having issues on php8 branch with printing detail pages to PDF as it didn't seem to be obeying the css file.
I finally narrowed it down to not using wkhtmltopdf library as the external_applications only has it pointed to the one place `/usr/bin/local` instead of multiple location.   I copied the providence conf over to pawtucket and the pdf generation started to work correctly. 

I am unsure if some of the applications listed in the pawtucket conf (but not in the providence conf) are still needed or not, so didn't want to just submit a pull request with a providence copy.

**Comment by collectiveaccess** [comment]
I updated the config file. It was indeed out of date.

**Comment by Monica-Wood** [comment]
thank you
