### ISSUE TITLE
Thumbnail Click Not Updating Representation Viewer

### ISSUE THREAD

**Issue by ChiaChing-Yen** [collectiveaccess/pawtucket2#112]
On object detail view, clicking thumbnails fails to update the representation viewer for objects with multiple representations.

## Steps to Reproduce

- PHP version: 8.1.29, Git clone from `dev/php8` branch then Composer install
- Use Dublin Core profile (2018), leave everything else in default
- Create new object with two different representations
- On detail view, click different thumbnails

**Comment by miqrogroove** [comment]
I'm working on an implementation for this.  Javascript is not my language, but this feature is important for me.

**Comment by collectiveaccess** [comment]
It was reimplemented already to avoid using jcarousel, which is the cause of the issue. Older themes will need to change the "linkTo" option in caObjectRepresentationThumbnails(). This is usually called in the object detail views. I've just pushed a change to default to account for this. It had only been set in themes we actively develop previously.

**Comment by miqrogroove** [comment]
I can build off of that.  There still a bunch of code missing.

**Comment by collectiveaccess** [comment]
What exactly is incomplete?

**Comment by miqrogroove** [comment]
See #123, #124, and #127.
