### ISSUE TITLE
Elastic indexer not indexing important zero values like deleted = 0, and search not working.

### ISSUE THREAD

**Issue by oldnewnick** [collectiveaccess/pawtucket2#134]
https://github.com/collectiveaccess/pawtucket2/blob/e4a0e5e024ea21f67dc1d3c9a3564935881efc92/app/lib/Search/SearchIndexer.php#L810

when $pa_field_data[$vs_field] = 0 condition is false and important values, like deleted = 0 in DB is not indexed, and then all elastic index is missing this field causing search not work as in search there is explicitly set `AND deleted = 0` for all queries in :

https://github.com/collectiveaccess/pawtucket2/blob/e4a0e5e024ea21f67dc1d3c9a3564935881efc92/app/lib/Search/SearchEngine.php#L277C1-L285C5

**Comment by collectiveaccess** [comment]
Fixed in Providence
