### ISSUE TITLE
overflow / max-height css doesn't seem to be working for the browse menu in `/dev/php8` branch

### ISSUE THREAD

**Issue by 0nobody0** [collectiveaccess/pawtucket2#136]
(note: first had to disable the browse menu list format by setting `browseMenuFormat =` in `browse.conf`)

when there are many results for a browse facet the browse menu extends all the way down the page to the final facet entry. adding `max-height: 325px` and `overflow: auto` to  .filterMenuResults seems to fix the problem, or at least seems to be a temporary workaround?

https://github.com/collectiveaccess/pawtucket2/blob/e8e187e7c96a39a37842512b02127a802940b4c0/themes/default/assets/pawtucket/css/main.css#L623-L625

**Comment by mariamotorina** [comment]
Thanks, just pushed a fix for that.
