### ISSUE TITLE
Wikipedia InformationService not retrieving information

### ISSUE THREAD

**Issue by flumpt** [collectiveaccess/pawtucket2#18]
Hello,

I recently discovered that the InformationService for Wikipedia is not able to retrieve the information in our project. After some investigation I found that the Wikipedia API is responding with the following error:

`{"error":{"code":"badinteger","info":"Invalid value \"200px\" for integer parameter \"pithumbsize\".","*":"See https://de.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."},"servedby":"mw1277"}`

I reckon this problem arises due to a change in the API.  I tackled the problem by removing the 'px' in the InformationService for Wikipedia:
https://github.com/collectiveaccess/pawtucket2/blob/a051f2fe919ca4657340c2ba8d7dcbbfda933a15/app/lib/Plugins/InformationService/Wikipedia.php#L157

Can you confirm that this change is correct and maybe implement it?

Best regards and stay healthy!

**Comment by collectiveaccess** [comment]
Yes, we noticed this too. It's already fixed in the "develop" branch, with a similar fix.

Thanks!

**Comment by flumpt** [comment]
Alright! Thank you for the quick response.
