### ISSUE TITLE
themeHelpers: SQL broken when browsing Object_lots

### ISSUE THREAD

**Issue by bruceklotz** [collectiveaccess/pawtucket2#27]
Attempting to browse Ca_Object_lots will throw an error: "Object_lots: Not unique table/alias: 'ca_objects' in /...." 

Unless the SQL is modified (in themeHelpers.php) adding "as ca_objectsx":

$vs_sql = "SELECT DISTINCT ca_object_representations.media, {$vs_table}.{$vs_pk}
FROM {$vs_table}
INNER JOIN {$vs_linking_table} ON {$vs_linking_table}.{$vs_pk} = {$vs_table}.{$vs_pk}
INNER JOIN ca_objects as ca_objectsx ON ca_objects.object_id = {$vs_linking_table}.object_id
INNER JOIN ca_objects_x_object_representations ON ca_objects_x_object_representations.object_id = ca_objects.object_id
INNER JOIN ca_object_representations ON ca_object_representations.representation_id = ca_objects_x_object_representations.representation_id
WHERE
ca_objects_x_object_representations.is_primary = 1 {$vs_access_wheres} {$vs_rel_type_where} {$vs_type_where} {$vs_id_sql}";

And changing $va_access_wheres to:
$vs_access_wheres = " AND ca_objectsx.access IN (".join(",", $pa_access_values).") AND ca_object_representations.access IN (".join(",", $pa_access_values).")";

**Comment by collectiveaccess** [comment]
I assume this is in Pawtucket. Could you tell me what the exact version is that you're using?
