### ISSUE TITLE
Entities without IDs do not reolve when use_identifiers_in_urls = 1

### ISSUE THREAD

**Issue by dullj** [collectiveaccess/pawtucket2#30]
We've copied things to a new server, updated from 1.7.9 to 1.7.13 (db schema 158), and created a new theme. 

When `use_identifiers_in_urls` was set to 0 in the new theme, the URLs resolved correctly. When we changed the value to 1, entities without IDs no longer resolve and the URL encoding seems to not work. We did not have this issue in our past installation. I'm trying to track down where this is happening. Here are examples from the 2 servers old and new.
Old install: https://digitalarchives.library.newschool.edu/index.php/Detail/people/id%3A4079
New Install: https://dev-digital.archives.newschool.edu/index.php/Detail/entities/id%3A4079

if you manually replace the '%3A' with the deencoded ':', the URL resolves correctly.

**Comment by collectiveaccess** [comment]
We'll get to it when we can.

**Comment by collectiveaccess** [comment]
Just pushed a fix for this. Please do a pull on master and let me know if it works for you. If it does we'll put it in a 1.7.14 release.
