### ISSUE TITLE
Filename Corruption Upon Download

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/pawtucket2#34]
Steps to reproduce bug:

- Upload a media file containing an ampersand (&) in the name.
- First tested with the BinaryFile plugin.  For example, `John & Jane.pspimage`
- Additional testing showed same result with JPG files when downloading through Pawtucket.

Expected result:

- Name should appear correctly in the media section.
- Upon clicking the Download link in Pawtucket, the original filename or a reasonable substitute should be provided.

Actual result:

- Name is correct in media section.
- Upon download, the provided filename is corrupted like `John_&amp` with incomplete name and no extension.

Workaround:

It would be necessary to change the filename prior to upload.  I had attempted to add the `Original filename` field to the Object representation editor; it displays the name but will not save any changes.

**Comment by collectiveaccess** [comment]
Got it thanks. We will resolve.

**Comment by miqrogroove** [comment]
Workaround #2: Edit the `downloaded_file_naming` preference in `themes/default/conf/app.conf`

Workaround #3: at https://github.com/collectiveaccess/pawtucket2/blob/84dbafa54fa2b7724931ab5d992fc9a7a248a01e/themes/default/views/Details/object_representation_download_binary.php#L37 
... Change the whole line as follows ...

```
$dname = htmlspecialchars_decode($this->getVar('version_download_name'), ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401);

header("Content-Disposition: attachment; filename=\"$dname\"");
```

**Comment by collectiveaccess** [comment]
Push changes to resolve this to master.
