### ISSUE TITLE
Image Viewer Needs Touch Support

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/pawtucket2#35]
Is there an updated version of the included image viewer?  It works great with a mouse and keyboard, but on my touch screen I can't pan or pinch zoom at all.

**Comment by collectiveaccess** [comment]
That's the current version.

**Comment by miqrogroove** [comment]
On Windows there are some workarounds, but on Android this image viewer doesn't work for me.

**Comment by miqrogroove** [comment]
Part of the problem is the Image Overview feature is broken.  It doesn't work right with a mouse or touch screen in any browser I've tried.  This leaves mouse panning as the only means of navigation.  If the tile viewer isn't going to get updates then I hope that part can be replaced with something newer.

**Comment by collectiveaccess** [comment]
Really? How exactly is it broken? It does what it's supposed to via mouse clicks in Chrome/Safari/Firefox.

**Comment by miqrogroove** [comment]
To be fair, the Image Overview works at some zoom levels and not others.  For example, go here and zoom in about 25%

https://kress.nga.gov/Detail/objects/3483

When full out or full in it does work.  But with the slider about 25% to 33% from the left, that overview thing is not working the same way.

**Comment by collectiveaccess** [comment]
Oh I see the issue now. Thanks for finding this. We're not scaling coordinates when we pan, which doesn't make much of a difference at closer magnifications, but blows up when pulled out a bit.

**Comment by miqrogroove** [comment]
I copied this file to my server and refreshed in Chrome https://raw.githubusercontent.com/collectiveaccess/pawtucket2/develop/assets/jquery/jquery-tileviewer/jquery.tileviewer.js

Seems to be much better, however around 50% zoom I'm unable to pan to the bottom or right edges.  Should I open a new issue?

**Comment by miqrogroove** [comment]
Nevermind, I found the correct math for this.  I will open a new PR for you.

**Comment by miqrogroove** [comment]
See #39

**Comment by miqrogroove** [comment]
All of the above problems still exist in v1.7.16.  See #46 for the scrolling patch to master.
