### ISSUE TITLE
"Share This Item" Generates Email Blob

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/pawtucket2#36]
After clicking the "Share" link on a Details page and completing the email form, Pawtucket generates a multipart message including what appears to be a malformed thumbnail attachment.  The payload begins with:

```
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment
```

After that, my email client creates a generic filename with no extension.  I had to open this in a text editor to find out that it was supposed to be an image.  So, this is taking up space in the message and doing nothing else.

**Comment by collectiveaccess** [comment]
It's a valid image when I just tried it. We can change the content-type to hopefully make you and your email client happy.

**Comment by miqrogroove** [comment]
I tried Gmail and Thunderbird.  Both show this file as an anonymous blob.  Gmail calls it `noname` and Thunderbird calls it `Part 1.2`

**Comment by collectiveaccess** [comment]
Pushed change (a37b8254f316555a44c6568d6b98dd34492ba23f) to set mime type for attachments.
