### ISSUE TITLE
Detail Thumbnails Sometimes Link to Wrong Image

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/pawtucket2#37]
When an object has several representations, scrolling through the images on the Detail page only works when using the arrow links.  After loading or reloading the page, clicking any thumbnail other than the first one will advance to the wrong image.

**Comment by collectiveaccess** [comment]
Works fine on test and demo systems. I'll guess you have use_universal_viewer_for_image_list_length_at_least = 4 (or something like that) set in media_display.conf. That'll force images into the multipage document viewer, which you might see as not respecting your clicks (it just shows all thumbnails + first page on load).  Try removing use_universal_viewer_for_image_list_length_at_least from your config and see if that helps.

**Comment by miqrogroove** [comment]
I couldn't see any difference by changing that number in the app or theme files.

Where is the pawtucket demo system?

**Comment by miqrogroove** [comment]
p.s. I was able to see the universal viewer by setting `viewer = UniversalViewer` in the theme's conf but the other list length setting seems to have no effect.  Either way, this is not the same symptom I was seeing earlier.  I opened a new issue for clarity.
