### ISSUE TITLE
Searching on open quotes causes fatal error

### ISSUE THREAD

**Issue by katiemartinez** [collectiveaccess/pawtucket2#77]
Performing a search in Pawtucket with one set of quotation marks at the start of a phrase or word ("new york) causes the following fatal error: 

Fatal error: Uncaught Error: Call to undefined method Zend_Search_Lucene_Index_Term::getTerm() in /var/www/pawtucket/app/helpers/searchHelpers.php:883 Stack trace: #0 /var/www/pawtucket/app/lib/pawtucket/BaseMultiSearchController.php(95): caGetDisplayStringForSearch('"new york') #1 /var/www/pawtucket/app/controllers/MultiSearchController.php(59): BaseMultiSearchController->Index(NULL) #2 /var/www/pawtucket/app/lib/Controller/RequestDispatcher.php(281): MultiSearchController->Index(NULL) #3 /var/www/pawtucket/app/lib/Controller/AppController.php(113): RequestDispatcher->dispatch(Array) #4 /var/www/pawtucket/index.php(132): AppController->dispatch(true) #5 {main} thrown in /var/www/pawtucket/app/helpers/searchHelpers.php on line 883

Quotes elsewhere in the search bar are fine (new york" / "new york" / new " york). 

We are currently running 1.7.13 for Pawtucket and 1.7.17 for Providence. This issue is occurring our our digital collections site (https://digital.archives.newschool.edu) as well as others (for example: https://kress.nga.gov/).  

Pawtucket is behind Providence because the updated version ignores hyphens in record identifiers, and prevents those pages from loading.

**Comment by collectiveaccess** [comment]
Resolved in dev/php8
