### ISSUE TITLE
MultiSearch Sorted by Relevance, Full Results Sorted by ID

### ISSUE THREAD

**Issue by miqrogroove** [collectiveaccess/pawtucket2#78]
When using the Search box in the default theme, I'm sent to `/MultiSearch/Index` with results sorted by relevance.  This is useful because some search results are low relevance due to matching things like an object's collection's meta values.

When I click the "FULL RESULTS" link, I'm sent to `/Search/objects/search/` where the only sort options are Identifier and Title.

This inconsistency can be very frustrating.

**Comment by collectiveaccess** [comment]
You can add relevance to the sort options in the primary search if you wish.
