### ISSUE TITLE
Access points not searching as AND boolean

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/pawtucket2#82]
When searching on multiple access points with AND or no boolean, it is return results as if you searched with OR. 
eg.  type_id='journal' AND abstract='text to search'  This returns all results as an OR boolean instead.

If you search on the same fields using full notion (eg. ca_objects.typeid='journal' AND ca_objects.abstract="text to search") then it returned as you would expect.

**Comment by collectiveaccess** [comment]
Ok
