### ISSUE TITLE
caUtils error

### ISSUE THREAD

**Issue by ewshop8** [collectiveaccess/pawtucket2#87]
When a start support/bin/caUtils a get this error:
PHP Fatal error:  Trait method replicate_data has not been applied, because there are collisions with other trait methods on CLIUtils in /var/www/html/providence/pawtucket2/app/lib/Utils/CLIUtils.php on line 51

**Comment by collectiveaccess** [comment]
What version are you running?

**Comment by ewshop8** [comment]
Pawtucket2 Version 1.8 developVerzonden vanaf Outlook voor Android
