### ISSUE TITLE
Reference to manuscriptcookbook inside Maps plugin

### ISSUE THREAD

**Issue by gautiermichelin** [collectiveaccess/pawtucket2#9]
Hello,

At this line : 
https://github.com/collectiveaccess/pawtucket2/blob/78650105656a6f5709b5bdeb1d72f8ebf586d8b4/app/lib/core/Plugins/GeographicMap/GoogleMaps.php#L297 and 3/4 lines after that is a reference to : 
http://manuscriptcookbook.whirl-i-gig.com/pawtucket/assets/ca/js/mcs_marker.png

The image is not there on this server, but it is there inside pawtucket/assets/ca/js/mcs_marker.png

**Comment by collectiveaccess** [comment]
This was fixed in develop branch and will be in the next release.

**Comment by gautiermichelin** [comment]
Thanks for the quick answer :-)
