### ISSUE TITLE
PHP Fatal Error, replicate_data method 

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/pawtucket2#90]
https://github.com/collectiveaccess/pawtucket2/blob/c7f0063e6e69031e40c743a3b0200dd674eaccd1/app/lib/Utils/CLIUtils/ImportExport.php#L813

Some sneaky extra lines of code have duplicated themselves into the importExport.php from Replication.php.

edit: Looks like there were meant to be removed from importExport.php when Replication.php was created. :)

When trying to run caUtils from pawtucket, getting the following error
`PHP Fatal error:  Trait method replicate_data has not been applied, because there are collisions with other trait methods on CLIUtils in /var/www/html/pawtucket/app/lib/Utils/CLIUtils.php on line 51`

**Comment by collectiveaccess** [comment]
This was fixed a while back. When was the last time you did a pull?

**Comment by Monica-Wood** [comment]
I did the pull today. Upgraded from master to develop.
