### ISSUE TITLE
Collection facet not showing top level

### ISSUE THREAD

**Issue by Monica-Wood** [collectiveaccess/pawtucket2#94]
I have a dev system with both providence and pawtucket on the newest dev/php8 (pulled today).

It's set up with the ca_objects_x_collections_hierarchy_enabled. 

The following facet is set in both providence and pawtucket under ca_objects

```	
    collection_facet = {
			type = authority,
			table = ca_collections,
			relationship_table = ca_objects_x_collections,
			restrict_to_types = [],
			restrict_to_relationship_types = [],
			
			group_mode = alphabetical,
			
			label_singular = _("collection"),
			label_plural = _("collections")
		},
```

In providence it shows  all levels of the hierarchy (collection, series etc) even if it's not the direct parent, and if I `restrict_to_types = [collection]` then it will only show the top level... this is what I am after.

but in Pawtucket, it will only show the immediate collection related to the object and if I was the restrict to collection type, then only top level collections directly related to the object will show.

Is there something in indexing causing this, or have I found a bug?

Thank you.
Monica

**Comment by collectiveaccess** [comment]
I'd make sure you don't have the `dontExpandTypesHierarchically` option set. That would cause the behavior you're seeing. 

I just tried your facet configuration on a working site with a deep collection hierarchy and archival items (and `dontExpandTypesHierarchically` for the facet not set), and it's showing top level collections when restricted.

**Comment by Monica-Wood** [comment]
I have the facet set up exactly as you see here.  When I was playing to try and get it working I had tried the `group_mode = hierarchical`. And I had the `dontExpandTypesHierarchically` set for a bit to see what it would do, But I didn't want the hierarchy selector so removed it again. I'll try clearing caches again in case, but thought I had browse cache set to 0.
