### ISSUE TITLE
Suspected bug in SearchResult.php with access control

### ISSUE THREAD

**Issue by ebarthel** [collectiveaccess/pawtucket2#95]
Hi,
with Pawtucket 1.7.11, with access control on, using the "sibling" filter for formatting in ca_objects_default_html.php as p.e.
<unit relativeTo="ca_objects.siblings" delimiter=" - ">
results in the error pasted below.
It is caused by the 
{$vs_access_sql} clause in the SQL instruction
$vs_sql = "
			SELECT t.{$vs_pk}, t.{$vs_parent_id_fld}, p.{$vs_pk} sibling_id
			FROM {$ps_tablename} AS t
			INNER JOIN {$ps_tablename} AS p ON t.{$vs_parent_id_fld} = p.{$vs_parent_id_fld}
			WHERE
				 t.{$vs_pk} IN (?)".($t_rel_instance->hasField('deleted') ? " AND (t.deleted = 0) AND (p.deleted = 0)" : "")."
					 {$vs_type_sql}
--					 {$vs_access_sql}
		";
on line 601 in SearchResult.php
I suppressed the clause and the error no longer shows up. There is no functionality change in my case but I suspect this is a bug.
Thanks,
Etienne

***************************************
Something went wrong
Unknown column 'ca_objects.access' in 'where clause' in /home/augusteb/www/CA/CA_EM/vision/app/lib/Db/mysqli.php line 316:

    In Db_mysqli->execute(Object DbStatement, Object DbStatement, ' SELECT t.object_id, t.parent_id, p.object_id sibling_id FROM ca_objects AS t INNER JOIN ca_objects AS p ON t.parent_id = p.parent_id WHERE t.object_id IN (?) AND (t.deleted = 0) AND (p.deleted = 0) AND (ca_objects.access IN (1)) ', Array(1), ) in DbStatement line 151
    At DbStatement->executeWithParamsAsArray(Array(1), ) in Db line 259
    At Db->query(' SELECT t.object_id, t.parent_id, p.object_id sibling_id FROM ca_objects AS t INNER JOIN ca_objects AS p ON t.parent_id = p.parent_id WHERE t.object_id IN (?) AND (t.deleted = 0) AND (p.deleted = 0) AND (ca_objects.access IN (1)) ', Array(1)) in SearchResult line 611
    At SearchResult->prefetchHierarchySiblings('ca_objects', 0, 50, Array(13)) in SearchResult line 1466
    At SearchResult->get('ca_objects.siblings.object_id', Array(13)) in ObjectSearchResult line 104
    At ObjectSearchResult->get('ca_objects.siblings.object_id', Array(11)) in DisplayTemplateParser line 601
    At DisplayTemplateParser::_processChildren(Object ObjectSearchResult, Array(1), Array(0), Array(3)) in DisplayTemplateParser line 426
    At DisplayTemplateParser::_processChildren(Object ObjectSearchResult, Array(3), Array(1), Array(3)) in DisplayTemplateParser line 852
    At DisplayTemplateParser::_processChildren(Object ObjectSearchResult, Array(2), Array(1), Array(3)) in DisplayTemplateParser line 259
    At DisplayTemplateParser::process('
    ^ca_objects.preferred_labels.name^ca_objects.preferred_labels.name
    ', 'ca_objects', Array(1), Array(2)) in DisplayTemplateParser line 59
    At DisplayTemplateParser::evaluate('
    ^ca_objects.preferred_labels.name^ca_objects.preferred_labels.name
    ', 'ca_objects', Array(1), Array(1)) in displayHelpers line 2452
    At caProcessTemplateForIDs('
    ^ca_objects.preferred_labels.name^ca_objects.preferred_labels.name
    ', 'ca_objects', Array(1), Array(1)) in BundlableLabelableBaseModelWithAttributes line 690
    At BundlableLabelableBaseModelWithAttributes->getWithTemplate('
    ^ca_objects.preferred_labels.name^ca_objects.preferred_labels.name
    ', Array(1)) in displayHelpers line 4330
    At caDoTemplateTagSubstitution(Object View, Object ca_objects, 'Details/ca_objects_default_html.php', Array(1)) in DetailController line 476
    At DetailController->__call('objects', Array(1)) in RequestDispatcher line 273
    At RequestDispatcher->dispatch(Array(2)) in AppController line 113
    At AppController->dispatch(true) in index line 124

Request parameters:

    collectiveaccess => 3d3033c7-25e5-409c-89a3-d0e45fd3c5cc
    CA_collectiveaccess_ui_locale => fr_FR

**Comment by collectiveaccess** [comment]
1.7.11 is quote old. You should update. Removing that cause means that siblings will no longer be suppressed if their access is set to private.

**Comment by ebarthel** [comment]
I tried in 1.7.15 - the same problem occurs.
However I have changed
592			$vs_access_sql = " AND ({$ps_tablename}.access IN (".join(",", $pa_options['checkAccess']) ."))";	
into
592 			$vs_access_sql = " AND ({p.access IN (".join(",", $pa_options['checkAccess']) ."))";	
in SearchResult.php and it seems to work.

**Comment by collectiveaccess** [comment]
Thanks for checking. We'll take a closer look.

**Comment by collectiveaccess** [comment]
I see it. Your fix is the correct one. We'll put it into Git and into a new release soon. Thanks.
